/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.edu.satc.form;

import br.edu.satc.objetos.Grupo;
import br.edu.satc.objetos.Lobo;
import br.edu.satc.objetos.Peixe;
import br.edu.satc.objetos.Zoologico;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class TelaAnimal extends javax.swing.JFrame {
    Zoologico z = new Zoologico();
    void desabilitarLobo(){
    this.jTFDataNascimentoLobo.setEnabled(false);
    this.jTFPesoLobo.setEnabled(false);
    this.jTFTamanhoLobo.setEnabled(false);
    }
     void habilitarLobo(){
    this.jTFDataNascimentoLobo.setEnabled(true);
    this.jTFPesoLobo.setEnabled(true);
    this.jTFTamanhoLobo.setEnabled(true);
     }
    void desabilitarPeixe() {
    this.jTFTipo.setEnabled(false);
    }
    void habilitarPeixe(){
      this.jTFTipo.setEnabled(true);  
  }

    /**
     * Creates new form TelaAnimal
     */
    public TelaAnimal() {
        initComponents();
        desabilitarLobo();
        desabilitarPeixe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloDoForm = new javax.swing.JLabel();
        jBCadastro = new javax.swing.JButton();
        jBConsultaCadastrados = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLGrupo = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFDescricao = new javax.swing.JTextField();
        jRBPeixe = new javax.swing.JRadioButton();
        jRBLobo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLAnimal = new javax.swing.JLabel();
        jLDescriçãoAnimal = new javax.swing.JLabel();
        jLStatusdoAnimal = new javax.swing.JLabel();
        jTFDescriçaoAnimal = new javax.swing.JTextField();
        jTFStatusAnimal = new javax.swing.JTextField();
        jPLobo = new javax.swing.JPanel();
        jTFPesoLobo = new javax.swing.JTextField();
        jTFTamanhoLobo = new javax.swing.JTextField();
        jTFDataNascimentoLobo = new javax.swing.JTextField();
        jLPesoLobo = new javax.swing.JLabel();
        jLTamanhoLobo = new javax.swing.JLabel();
        jLDatadeNascimentoLobo = new javax.swing.JLabel();
        jLLobo = new javax.swing.JLabel();
        jPPeixe = new javax.swing.JPanel();
        jLPeixe = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jTFTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTituloDoForm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLTituloDoForm.setText("CADASTRO DE ANIMAIS ");

        jBCadastro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBCadastro.setText("Cadastro");
        jBCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastroActionPerformed(evt);
            }
        });

        jBConsultaCadastrados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBConsultaCadastrados.setText("Consulta Cadatrados");
        jBConsultaCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaCadastradosActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLGrupo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLGrupo.setText("GRUPO");

        jLNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLNome.setText("Nome");

        jLDescricao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLDescricao.setText("Descrição");

        jTFDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDescricao)
                            .addComponent(jLGrupo)
                            .addComponent(jLNome))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addComponent(jTFDescricao))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLGrupo)
                .addGap(57, 57, 57)
                .addComponent(jLNome)
                .addGap(4, 4, 4)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jRBPeixe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRBPeixe.setText("Peixe");
        jRBPeixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPeixeActionPerformed(evt);
            }
        });

        jRBLobo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRBLobo.setText("Lobo");
        jRBLobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLoboActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLAnimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLAnimal.setText("Animal");

        jLDescriçãoAnimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLDescriçãoAnimal.setText("Descrição");

        jLStatusdoAnimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLStatusdoAnimal.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLAnimal)
                    .addComponent(jLDescriçãoAnimal)
                    .addComponent(jLStatusdoAnimal)
                    .addComponent(jTFDescriçaoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jTFStatusAnimal))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAnimal)
                .addGap(40, 40, 40)
                .addComponent(jLDescriçãoAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTFDescriçaoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLStatusdoAnimal)
                .addGap(1, 1, 1)
                .addComponent(jTFStatusAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPLobo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLPesoLobo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLPesoLobo.setText("Peso");

        jLTamanhoLobo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLTamanhoLobo.setText("Tamanho");

        jLDatadeNascimentoLobo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLDatadeNascimentoLobo.setText("Data Nascimento");

        jLLobo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLLobo.setText("Lobo");

        javax.swing.GroupLayout jPLoboLayout = new javax.swing.GroupLayout(jPLobo);
        jPLobo.setLayout(jPLoboLayout);
        jPLoboLayout.setHorizontalGroup(
            jPLoboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLoboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFPesoLobo)
                    .addComponent(jTFTamanhoLobo)
                    .addComponent(jTFDataNascimentoLobo)
                    .addGroup(jPLoboLayout.createSequentialGroup()
                        .addGroup(jPLoboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDatadeNascimentoLobo)
                            .addComponent(jLTamanhoLobo)
                            .addComponent(jLPesoLobo)
                            .addComponent(jLLobo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPLoboLayout.setVerticalGroup(
            jPLoboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLLobo)
                .addGap(36, 36, 36)
                .addComponent(jLPesoLobo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPesoLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLTamanhoLobo)
                .addGap(8, 8, 8)
                .addComponent(jTFTamanhoLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLDatadeNascimentoLobo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTFDataNascimentoLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPPeixe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLPeixe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLPeixe.setText("Peixe");

        jLTipo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLTipo.setText("Tipo");

        javax.swing.GroupLayout jPPeixeLayout = new javax.swing.GroupLayout(jPPeixe);
        jPPeixe.setLayout(jPPeixeLayout);
        jPPeixeLayout.setHorizontalGroup(
            jPPeixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPeixeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPeixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTipo)
                    .addGroup(jPPeixeLayout.createSequentialGroup()
                        .addGroup(jPPeixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPeixe)
                            .addComponent(jLTipo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPPeixeLayout.setVerticalGroup(
            jPPeixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPeixeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLPeixe)
                .addGap(18, 18, 18)
                .addComponent(jLTipo)
                .addGap(18, 18, 18)
                .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConsultaCadastrados)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTituloDoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBPeixe)
                                .addGap(18, 18, 18)
                                .addComponent(jRBLobo))
                            .addComponent(jBCadastro)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPPeixe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTituloDoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBPeixe)
                            .addComponent(jRBLobo))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsultaCadastrados)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPLobo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPPeixe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastroActionPerformed
          if(jRBLobo.isSelected()){
              float pesoLobo=' ';
              float tamanhoLobo=' ';
          Date dataNascimentoLobo = null;
          String descricaoGrupoLobo,nomeGrupoLobo, descricaoAnimalLobo;
          char statusLobo= ' ';
          try{
             pesoLobo = Float.parseFloat(jTFPesoLobo.getText());
          }catch(NumberFormatException nfe){
              JOptionPane.showMessageDialog(this, nfe);
              return;
          }
          try{
          tamanhoLobo = Float.parseFloat(jTFTamanhoLobo.getText());
          }catch(NumberFormatException nfe){
              JOptionPane.showMessageDialog(this, nfe);
              return;
          }
          SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                  dataNascimentoLobo = sdf.parse(jTFDataNascimentoLobo.getText());
            } catch (ParseException ex) {
               JOptionPane.showMessageDialog(this, ex);
            }
          descricaoGrupoLobo = jTFDescricao.getText();
          nomeGrupoLobo = jTFNome.getText();
          descricaoAnimalLobo = jTFDescriçaoAnimal.getText();
          try{
          statusLobo = jTFStatusAnimal.getText().toUpperCase().charAt(0);
          }catch(StringIndexOutOfBoundsException sioobe){
              JOptionPane.showMessageDialog(this, sioobe);
              return;
          }
          
          z.getAnimais().add(new Lobo(pesoLobo,tamanhoLobo,dataNascimentoLobo,new Grupo(nomeGrupoLobo,descricaoGrupoLobo),descricaoAnimalLobo,statusLobo));
              
              
              
          }else if(jRBPeixe.isSelected()){
              String descricaoAnimal, nomeGrupo, descricaoGrupo;
              String tipo = null;
              char status =' ';
              descricaoAnimal = jTFDescriçaoAnimal.getText();
              nomeGrupo = jTFNome.getText();
              descricaoGrupo = jTFDescricao.getText();
              try{
              tipo = jTFTipo.getText();
              }catch(StringIndexOutOfBoundsException sioobe){
                  JOptionPane.showMessageDialog(this, sioobe);
                  return;
              }
              try{
              status = jTFStatusAnimal.getText().toUpperCase().charAt(0);
              }catch(StringIndexOutOfBoundsException sioobe){
                 JOptionPane.showMessageDialog(this, sioobe);
                 return;
              }
              z.getAnimais().add(new Peixe(tipo, new Grupo(nomeGrupo, descricaoGrupo), descricaoAnimal, status));
              
          }else{
              JOptionPane.showMessageDialog(this, "Favor escolher uma das opçoes \"Lobo ou Peixe\"" );
          }
    }//GEN-LAST:event_jBCadastroActionPerformed

    private void jBConsultaCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaCadastradosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, z.toString());
    }//GEN-LAST:event_jBConsultaCadastradosActionPerformed

    private void jRBPeixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPeixeActionPerformed
          if(jRBLobo.isSelected()){
              jRBLobo.setSelected(false);
              desabilitarLobo();
          }
          habilitarPeixe();
          
    }//GEN-LAST:event_jRBPeixeActionPerformed

    private void jRBLoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLoboActionPerformed
           if(jRBPeixe.isSelected()){
              jRBPeixe.setSelected(false);
              desabilitarPeixe();
          }
          habilitarLobo();
          
    }//GEN-LAST:event_jRBLoboActionPerformed

    private void jTFDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastro;
    private javax.swing.JButton jBConsultaCadastrados;
    private javax.swing.JLabel jLAnimal;
    private javax.swing.JLabel jLDatadeNascimentoLobo;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLDescriçãoAnimal;
    private javax.swing.JLabel jLGrupo;
    private javax.swing.JLabel jLLobo;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPeixe;
    private javax.swing.JLabel jLPesoLobo;
    private javax.swing.JLabel jLStatusdoAnimal;
    private javax.swing.JLabel jLTamanhoLobo;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTituloDoForm;
    private javax.swing.JPanel jPLobo;
    private javax.swing.JPanel jPPeixe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBLobo;
    private javax.swing.JRadioButton jRBPeixe;
    private javax.swing.JTextField jTFDataNascimentoLobo;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFDescriçaoAnimal;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPesoLobo;
    private javax.swing.JTextField jTFStatusAnimal;
    private javax.swing.JTextField jTFTamanhoLobo;
    private javax.swing.JTextField jTFTipo;
    // End of variables declaration//GEN-END:variables
}
